### ISSUE TITLE
Pop ups taking the place of a tiling window

### ISSUE THREAD

**Issue by Lord-Guckavin** [PapyElGringo/material-shell#1]
# Issue
When a pop up is opened it takes the full place of an window. 

### Albert Launcher 
![Screenshot from 2019-07-01 20-29-51](https://user-images.githubusercontent.com/39229886/60431721-92b94980-9c3f-11e9-89a9-42758034c71c.png)

### Gearly Email
![Screenshot from 2019-07-01 20-33-06](https://user-images.githubusercontent.com/39229886/60432095-900b2400-9c40-11e9-920c-fd71b769b3f1.png)

### Nautilus pop up
![Screenshot from 2019-07-01 20-35-30](https://user-images.githubusercontent.com/39229886/60432299-10318980-9c41-11e9-9804-04a43b10b2f6.png)

# Expected
pop up floating above parent window

## Example 
![1561979803](https://user-images.githubusercontent.com/39229886/60432444-70283000-9c41-11e9-8245-1e4d5da1e85b.png)

**Comment by paradoxxxzero** [comment]
As discussed on discord, the same happens with small windows like `gnome-screenshot`:
![Screenshot from 2019-07-03 15-32-26](https://user-images.githubusercontent.com/271144/60596176-bba91e00-9da8-11e9-9adb-cb8f523bfc18.png)
