### ISSUE TITLE
Application launchers not clickable until a category is clicked

### ISSUE THREAD

**Issue by logix2** [PapyElGringo/material-shell#10]
Application launchers (the ones displayed in the middle of the screen by Material Shell) are not clickable until I click on a category in the left panel, only then they work.

I'm using Gnome Shell 3.32.1 / Ubuntu 19.04.

**Comment by PapyElGringo** [comment]
So at start and when you close all window? Or even when you click on the + button?

**Comment by logix2** [comment]
At the start, when Gnome just started (after I've just logged in).

**Comment by logix2** [comment]
I did not try the "+" button to see if it activates it. The app list is shown as soon as you login, without having to click "+".
