### ISSUE TITLE
Material Shell not Activating

### ISSUE THREAD

**Issue by XeroOl** [PapyElGringo/material-shell#105]
Material Shell doesn't seem to do anything on my system, and instead just prevents gnome's native tiling from working.
```sh
xerool@xerool-pc:~/.local/share/gnome-shell/extensions/material-shell@papyelgringo$ git show
commit b8ded1b4052c4b0c81a838bdd504701712b441d6 (HEAD -> master, origin/master, origin/HEAD)
Author: PapyElGringo <adrien.peslerbe@bemyeye.com>
Date:   Mon Aug 26 16:47:28 2019 +0200
(trimmed)
```

journalctl outputs [this.](https://gist.github.com/XeroOl/6b981df1e2fa724f9ce26a67896f814a)

(I deleted like 200,000 lines of logs that happened before before today)

Explanation:
I'm expecting Material Shell to handle the window tiling.
Instead, it seems like no window tiling is done at all, and the tiling that's built into gnome is also disabled.
[Here](https://streamable.com/oxkb3) is a video of the issue.

**Comment by PapyElGringo** [comment]
What is your version of gnome-shell?

**Comment by XeroOl** [comment]
gnome-shell version is GNOME Shell 3.28.4

**Comment by PapyElGringo** [comment]
We currently only support GNOME Shell 3.32+

**Comment by nununoisy** [comment]
What distro are you on? I can help you install gnome-shell 3.32

**Comment by XeroOl** [comment]
I just upgraded from Ubuntu 18.04 LTS to Ubuntu 19.04, and material-shell works as intended.
