### ISSUE TITLE
Titlebars duplicated for some windows

### ISSUE THREAD

**Issue by mikekosulin** [PapyElGringo/material-shell#106]
```
commit d7ca487c50f09449bf35741dd06cc9b07190d2a0 (HEAD -> master, origin/master, origin/HEAD)
Author: PapyElGringo <adrien.peslerbe@bemyeye.com>
Date:   Fri Sep 6 09:27:44 2019 +0200
```
[journalctl /usr/bin/gnome-shell](https://gist.github.com/mikekosulin/20d741b3d54e181fa2a424940cee6c93)

1.  Update to d7ca487
2. Restart shell
3. Open ubuntu settings

[Screenshot](https://pasteboard.co/IwA5VJx.png)

**Comment by mikekosulin** [comment]
It was ok on 9b4e16d

**Comment by PapyElGringo** [comment]
Thanks for the feedback. Looking into it.

**Comment by PapyElGringo** [comment]
Should be fixed. Please check and close if it's good for you :)

**Comment by mikekosulin** [comment]
Awesome!
Thanks🐱
