### ISSUE TITLE
HDPI Support - Scaling to more than 100%

### ISSUE THREAD

**Issue by scouturier** [PapyElGringo/material-shell#11]
It is not possible to scale to anything more than 100% (base), doing so will get the apps and the bars to overlap on top of each other and break the layout.

This is pretty common on HDPI monitors.

**Comment by LyesSaadi** [comment]
Had the same problem, and it's very annoying. Everything is 2x smaller...

**Comment by PapyElGringo** [comment]
Can you share a screenshot?

**Comment by LyesSaadi** [comment]
![Screenshot](https://files.lyes.eu/Material%20Shell/Capture%20d%e2%80%99%c3%a9cran%20du%202019-07-04%2010-03-03.png)

**Comment by Cretezy** [comment]
![image](https://user-images.githubusercontent.com/2672503/60685274-27a28980-9e70-11e9-8a02-30b09f06d559.png)

Same here. 4K XPS

**Comment by Cretezy** [comment]
Looking through the code, seems like most places where it's 48px should be twice that. I've fixed the vertical panel, working on getting the top one working (current x4 it's size for some reason)

**Comment by Cretezy** [comment]
Created PR to fix this (not finished): https://github.com/PapyElGringo/material-shell/pull/25

You can use my branch until then:
`git clone https://github.com/Cretezy/material-shell.git ~/.local/share/gnome-shell/extensions/material-shell@cretezy`

**Comment by PapyElGringo** [comment]
should be good now
