### ISSUE TITLE
Provide option to disable backdrop dim

### ISSUE THREAD

**Issue by codycraven** [PapyElGringo/material-shell#120]
```
commit 3130886e15a81f293b7f0947697f5869ee8d85df
```

When using an application such as Google Meet or Slack that provides a small persistent floating window, all other windows are overlaid with the backdrop widget which makes using the desktop difficult.

This is mitigated in Google Meet since the floating window has a "hide" action, however is not dismissable in Slack.

Floating window focused:
![floating-window-focused](https://user-images.githubusercontent.com/1533965/66151173-9dcb9f00-e5cb-11e9-99ab-70e1901490ea.png)

Floating window blurred (browser focused):
![floating-window-blurred](https://user-images.githubusercontent.com/1533965/66151191-a7550700-e5cb-11e9-9175-37ad5b211365.png)

To solve this usability issue, I would like the ability to prevent the backdrop widget functionality for my desktop. I successfully solved the problem with a hacky CSS change:

```diff
diff --git a/stylesheet.css b/stylesheet.css
index 97251ce..91f52e0 100644
--- a/stylesheet.css
+++ b/stylesheet.css
@@ -121,4 +121,4 @@
   margin: 8px; }
 
 .backdrop-container {
-  background: rgba(0, 0, 0, 0.5); }
+  background: rgba(0, 0, 0, 0.0); }
```

I would like to develop this as a configurable option in Material Shell by:
- Add a new Toggle in Material Shell's "Tiling settings" to allow the user to control whether the transparent backdrop is used or not.
- Make a change in tilingManager/tilingLayouts/baseTiling.js that omits the backdrop when the backdrop is disabled.

I believe the option to disable this feature would not only allow users that don't like the dimming to disable it, but could have provided immediate relief for similar problems that have been encountered with the screen dimming until a proper solution for each case could be developed and merged. Examples:

- #117 (open)
- #54 (already addressed)

Please let me know if this proposed solution would be acceptable for the project so that I may begin the work and open a PR when ready. If this proposed solution is not acceptable, please let me know an alternative to this problem that would be.

**Comment by PapyElGringo** [comment]
We need to distinguish 2 different issues.

1- The Dialog backdrop missbehavior by overlaying the wrong windows or workspaces on some cases
2- Some windows are wrongly detected as  Dialog

In your exemple it's mostly the second case. This utility box is detected as Dialog and therefore is positionned above other windows and display a backdrop behind her.

We could provide an option to disable the backdrop behavior by indeed proposing a setting and then removed the backdrop in the baseTiling based on this setting. But it's won't change that your utility window is detected as Dialog and will be positioned at the center of your screen above other windows.

To fix your issue we would either need to disable all the dialog features or find a way to detect properly this window as utility window.

Which browser are you using?

**Comment by codycraven** [comment]
I'm all for fixing the core issue.

This is with Brave (a Chromium based browser, I'll check if Firefox and Chrome also reproduce). This also occurs with the Slack client (an Electron based application - Electron also uses Chromium).

**Comment by PapyElGringo** [comment]
Are you on Xorg or Wayland?

**Comment by codycraven** [comment]
Sorry I should have included that: Xorg

Reproduced issue when screen sharing in Chrome.

Not reproduce-able in Firefox because Firefox does not create the window show in the screenshot when screen sharing.

**Comment by codycraven** [comment]
I also just reproduced this with the Zoom client (another screenshare/meeting application).

![zoom-focused](https://user-images.githubusercontent.com/1533965/66257923-edd56d80-e753-11e9-9ce8-dd826359b61f.png)

![zoom-blurred](https://user-images.githubusercontent.com/1533965/66257924-f168f480-e753-11e9-9512-1a3236388449.png)

**Comment by nununoisy** [comment]
The update prompt dialog in Firefox also causes this issue.

**Comment by codycraven** [comment]
Is there a desire for this new feature or will each instance be handled with separate code changes? I'm happy to create the code to expose it as a toggle in the UI, but I want to know that it will be acceptable to the project (pending PR approval of course) before performing the work.

**Comment by codycraven** [comment]
@PapyElGringo would you be open to this feature in the project or should we instead focus on fixing the individual instances that misbehave?

**Comment by PapyElGringo** [comment]
Can you defined the feature properly?

**Comment by codycraven** [comment]
@PapyElGringo add a new Toggle in Material Shell's "Tiling settings" to allow the user to control whether the transparent backdrop is used or not (default to enabled).

Make a change in tilingManager/tilingLayouts/baseTiling.js that omits the backdrop when the backdrop is disabled.

**Comment by codycraven** [comment]
I've reviewed and tested @nununoisy's solution, solves the need as intended (he beat me to it).
