### ISSUE TITLE
Cosmetic: verticalise panel-button indicators

### ISSUE THREAD

**Issue by myleftshoe** [PapyElGringo/material-shell#122]
Since the status area is verticalised, maybe the indicators should be too? 
You can do it with this css:

```
.panel-button:active, .panel-button:focus, .panel-button:checked {
  box-shadow: inset 3px 0 0px #3f51b5;
}
```
Before:
![panel-button-before](https://user-images.githubusercontent.com/32611040/66354217-da264300-e9af-11e9-8b04-1948530f061e.png)

After:
![panel-button](https://user-images.githubusercontent.com/32611040/66353810-ae568d80-e9ae-11e9-8764-365f5317fbc9.png)

**Comment by nununoisy** [comment]
I'd say do it on the right side instead of the left since it guides the eye toward the new content. But it definitely looks better.

**Comment by PapyElGringo** [comment]
Yep the only reason I didn't made it was because we lost the color of the shell theme. But when our theming engine will be done we will do this
