### ISSUE TITLE
System tray in the wrong place.

### ISSUE THREAD

**Issue by LyesSaadi** [PapyElGringo/material-shell#13]
Hi, this really is an amazing work you've been doing ! But with all new projects, when they're tested by everyone some bugs emerge :). And I have found one pretty annoying.
For an unknown reason, my system tray is in the top left corner of the screen, and sometimes it blocks the access to application menu.

**Comment by LyesSaadi** [comment]
Hi ! I think the issue is the same as #11 and because my resolution is twice as big as normal, the system tray appears on the top. (and the reason why there is overflow, is due to the fact that I activated seconds in my clock)

**Comment by PapyElGringo** [comment]
Can you share a screenshot?

**Comment by LyesSaadi** [comment]
![Screenshot](https://files.lyes.eu/Material%20Shell/Capture%20d%e2%80%99%c3%a9cran%20du%202019-07-04%2010-03-22.png)

**Comment by oct2pus** [comment]
haD0o#3983 on discord posted a work-around, if you enable/disable the battery percentage then the shell corrects itself until you next log out.

the flip seems to fix it, regardless of its previous setting and you can just flip it back with no ill effects.

**Comment by LyesSaadi** [comment]
You are a genius ! It just worked ! And now my sidebar is also opaque, which was alsoa bug, but not really problematic. I don't close the issue, because that's only a workaround, and still is a bug.
