### ISSUE TITLE
[Feature Request] Custom font of title bar and integrated keyboard launcher 

### ISSUE THREAD

**Issue by Titubery** [PapyElGringo/material-shell#143]
As the title, the font size is small for the height of title. And the launcher is  indispensible  for tiling WM just like [this](https://github.com/daniellandau/switcher), but it's not material. 
Thanks.

**Comment by nununoisy** [comment]
I can't say much for the first issue.

As for the second, are you using a material GTK theme? We recommend [Plata-theme](https://gitlab.com/tista500/plata-theme).
