### ISSUE TITLE
Suggestion: Chrome OS cursor theme

### ISSUE THREAD

**Issue by nununoisy** [PapyElGringo/material-shell#15]
[Here is a link to the theme](https://www.deviantart.com/dragonist08/art/Chrome-OS-Cursors-for-Ubuntu-534577672). It matches better than Adwaita does imo.

If necessary I will simplify the install process.

**Comment by PapyElGringo** [comment]
Im not sure I can include an icon them inside an extension

**Comment by nununoisy** [comment]
Sorry, I should have been clearer. Place it in README.md where the GTK and icon themes are

**Comment by PapyElGringo** [comment]
Is there the instructions to install them somewhere? I need to try them before deciding

**Comment by nununoisy** [comment]
1. Press the very small Download button underneath the image
2. Unzip the file
3. There are more directions inside, but basically run the script

**Comment by PapyElGringo** [comment]
I tryed it. Im not very fan of the installation instruction and the cursor icon is totally black it's not ideal for dark theme... So I'm not sure I want to showcase this :/
