### ISSUE TITLE
sidebar takes up whole screen

### ISSUE THREAD

**Issue by Targetednuke** [PapyElGringo/material-shell#159]
On Manjaro GNOME X.org, upon activating the extension, the top bar disappears, but the default dash to panel bar does not. The material-shell sidebar appears, but with no apps, and takes up the whole screen making it impossible to do anything. I installed it from the AUR. I don't know where I need to run *git show*, but I can if you need me to.
[journalctl.txt](https://github.com/PapyElGringo/material-shell/files/4131514/journalctl.txt)

**Comment by PapyElGringo** [comment]
You have a lot of extension that have error but the one that break Material-shell seem to be `appfolders-manager@maestroschan.fr` try to disable it.

**Comment by Targetednuke** [comment]
I disabled it, then reenabled material-shell, no difference. I will try to disable dash to panel, as that stays open while material-shell is active

**Comment by Targetednuke** [comment]
Fixed by updating all extensions, then removing Pomodoro timer, as it said it was throwing an error
