### ISSUE TITLE
Releases Tab on Github is empty

### ISSUE THREAD

**Issue by volodalexey** [PapyElGringo/material-shell#165]
Thanks for awesome extension!

There is no releases [here](https://github.com/PapyElGringo/material-shell/releases)

Can you please make/assign releases/versions so I can subscribe to the `Releases only` on this repo and update extensions whenever new version is available?

**Comment by PapyElGringo** [comment]
I'll try to fill it starting the 1.0 but until then you can follow the #announcements channel on Discord

**Comment by PapyElGringo** [comment]
Fixed :D
