### ISSUE TITLE
first release?

### ISSUE THREAD

**Issue by kloczek** [PapyElGringo/material-shell#170]
What do you think about tag first release? :)

**Comment by PapyElGringo** [comment]
FINE I'LL DO IT !

**Comment by PapyElGringo** [comment]
DONE :)

**Comment by kloczek** [comment]
Just a suggestion: because what is used by your extension is quite synced with gnome per se maybe it would be good to keep version which will indicate with which one version of the desktop it should be used?

In this case as first version it could be .3.36.0.

**Comment by PapyElGringo** [comment]
Well Material-shell should always compatible with the 2 latest versions of gnome-shell.

**Comment by kloczek** [comment]
Last two versions are 3.35.92 and 3.36.0 so using that as base point it should be 3.35.92 as the version string :)
