### ISSUE TITLE
Won't show in gnome-tweaks

### ISSUE THREAD

**Issue by moritz31** [PapyElGringo/material-shell#18]
Installed the extension like describe but even after a reboot it isn't showing up. 
Maybe some permission error or am i missing something?

**Comment by nununoisy** [comment]
Try `gnome-shell-extension-tool -e material-shell`

**Comment by pashtet422** [comment]
same problem. when i try `gnome-shell-extension-tool -e material-shell` i have response that material-shell is enabled but thats all, nothing changes.

**Comment by matthieugendreau** [comment]
Can you try Alt + F2 and enter r ? I had the same problem and it worked for me

(from https://askubuntu.com/a/98984/199925)

**Comment by matthieugendreau** [comment]
Can you try Alt + F2 and enter r ? I had the same problem and it worked for me.

(from https://askubuntu.com/a/98984/199925)

**Comment by pashtet422** [comment]
terminal output says: 'material-shell' is already enabled. alt + f2 r wont help

**Comment by PapyElGringo** [comment]
Well I have no clue... Can someone investigate on this while I fix other bugs? Thanks in advance :)

**Comment by maxwellium** [comment]
@moritz31 @pashtet422 following the readme will install the theme as "material-shell@papyelgringo". you would therefore have to enable it by `gnome-shell-extension-tool -e material-shell@papyelgringo`

(tested on ubuntu 19.04)

**Comment by pashtet422** [comment]
@maxwellium ty. that helps me!

**Comment by PapyElGringo** [comment]
Is that fixed? Do we know the source of the error?

**Comment by pashtet422** [comment]
> Is that fixed? Do we know the source of the error?
@PapyElGringo
yep. it`s my fault. I searched for gnome-shell theme instead of extention in my tweaks
