### ISSUE TITLE
ultrawide monitor

### ISSUE THREAD

**Issue by b4dtR1p** [PapyElGringo/material-shell#2]
Like i say u over reddit, tiling split so strange over ultrawide monitors and panel/bar dont work fine

also can u pls take us an option to move/delete the clock?

https://imgur.com/a/tbMBnWB here a pic to show u how strange is over ultrawide

**Comment by PapyElGringo** [comment]
Oh Material-shell seem to be broken!
Try disable others extensions it's probably interfering !

**Comment by Friede80** [comment]
This is also how it renders on my ultrawide monitor; one application on the left half of the screen, then all others added stack vertically on the right half. Is this the intended layout?

**Comment by PapyElGringo** [comment]
Well it's the way it's intended on normal screen. There isn't specific layout for ultrawide monitor yet. Just curious but what is the use of an ultrawide monitor? Gaming?

**Comment by Friede80** [comment]
Well first of all, it's awesome ;) But for me it let me do away with the dual monitors. No more bezel in my face. And of course its great for gaming.

Long story short, the ability to have 3 horizontal windows would be fantastic.

**Comment by chabad360** [comment]
While I don't have a ultrawide monitor, I would suggest that probably the best the way to with this would be to make the tiling system more modular (i.e. i3). Maybe it's even possible to provide a way to integrate this with i3...

**Comment by PapyElGringo** [comment]
You have now more tiling choices in the settings that should help here
