### ISSUE TITLE
"Home" tile so that I can admire my wallpaper and desktop shortcuts

### ISSUE THREAD

**Issue by PenetratingShot** [PapyElGringo/material-shell#22]
Add a "Home" icon above the Internet one which just looks like the normal desktop. I want to be able to look at my wallpaper and see my shortcuts :)

**Comment by PapyElGringo** [comment]
I don't see a real use case to that. And I try to keep the features list as minimal possible. Sorry...

**Comment by smolck** [comment]
@PapyElGringo Does this mean you also wouldn't provide an option to disable the application launcher entirely?

**Comment by PapyElGringo** [comment]
Well I'm not sure why we would like to do that. If it's to only admire the desktop I don't see a real use case. But you are not the first one who would like to do that but the previous one was mostly because the app launcher wasn't good enough and they preferred use the overview to launch app and I answered that I prefer work improving the app launcher that is integrated to our workflow than working to add an option to remove it...

**Comment by smolck** [comment]
> @smolck Well I'm not sure why we would like to do that. If it's to only admire the desktop I don't see a real use case. 

@PapyElGringo I guess it's just something we get used to from other desktop environments and/or window managers; regarding window managers (e.g. Sway), I've grown to like the minimalism of them, and the lack of much on the desktop besides a statusbar is more aesthetically pleasing in my personal opinion. But if you'd rather not add features and complexity solely for aesthetic purposes, I completely understand that.

However, what would you say to an option where the application launcher could be hidden _until you started typing_, so you can see your wallpaper and you get the clean aesthetic, but you still get the ability to search without having to use a keybinding to make the application launcher appear? Does that make sense?
 
> But you are not the first one who would like to do that but the previous one was mostly because the app launcher wasn't good enough and they preferred use the overview to launch app and I answered that I prefer work improving the app launcher that is integrated to our workflow than working to add an option to remove it...

I think the application launcher is perfectly fine, and having it easily accessible (i.e. available w/out pressing a keybinding) is nice. One thing I have noticed is that it is not possible to configure both the surface opacity of the background _and_ the surface opacity of the app launcher individually; changing "surface opacity" changes both of those things. It would be nice if I could have an almost opaque app launcher (so I can see the text under the icons with a light wallpaper) but the rest of the background transparent (so I can see my wallpaper around the app launcher).

**Comment by PapyElGringo** [comment]
@smolck The applauncher is meant to be usable with just a mouse so hiding it it's very mouse friendly but I think that all thoses ideas are valid but I'm not sure it should be prioritized over all the current pending features. But if you want to contribute to provide some options I'm not against !

**Comment by smolck** [comment]
> @smolck The applauncher is meant to be usable with just a mouse so hiding it it's very mouse friendly but I think that all thoses ideas are valid but I'm not sure it should be prioritized over all the current pending features. 

@PapyElGringo I agree hiding it is not mouse friendly, but I think providing the option to the users (some if not many of which I would presume prefer tiling wms, which aren't mouse friendly much if at all) would be cool. But such an option not being high priority is completely understandable.

> But if you want to contribute to provide some options I'm not against !

Awesome! I'd be happy to help make this a reality! If you wouldn't mind giving me some pointers though regarding what part of the code would need to be modified/added to, that would be wonderful, as I'm not familiar with the codebase. (Also, if there are other things like this that you don't have the time to work/aren't prioritizing, but that you'd like done, I'm happy to help out where I can!)

Oh and side note, thank you for working on this great project; it's really cool, and I probably wouldn't be using gnome without it. And thank you for the quick responses!

**Comment by PapyElGringo** [comment]
@smolck Maybe you can start by creating a new issue with a proper proposal so we could brainstorm around it (or other people interested on this) ?

**Comment by smolck** [comment]
@PapyElGringo Done: https://github.com/material-shell/material-shell/issues/257
