### ISSUE TITLE
Hamburger menu split

### ISSUE THREAD

**Issue by PenetratingShot** [PapyElGringo/material-shell#23]
The top half of the hamburger menu turns blue and shows the clock interface, while the bottom half opens up the application viewer. Can you unify this button into a single one which only displays the clock view?

**Comment by nununoisy** [comment]
This sounds like the clock is being misplaced (it should appear at the bottom). Do you have any extensions enabled that would move the clock or create toolbar icons?

**Comment by PapyElGringo** [comment]
duplicate of #13
