### ISSUE TITLE
Need a key shortcut to open the terminal

### ISSUE THREAD

**Issue by sigboe** [PapyElGringo/material-shell#3]
Need a key shortcut to open the terminal,

and it should be Super+Enter as default

**Comment by nununoisy** [comment]
This can be configured with GNOME by default.
+ Go to: Devices -> Keyboard
+ Scroll to the bottom and press the **+** sign
+ Enter a name (like 'Terminal'), the command to open your terminal (`gnome-terminal` or whatever you use), and the shortcut (Super+Enter)

**Comment by PapyElGringo** [comment]
Yeah I won't handle this in material-shell
