### ISSUE TITLE
Android Studio not playing nice with tiling

### ISSUE THREAD

**Issue by UbadahJ** [PapyElGringo/material-shell#32]
Android studio launch popup and similar dialog cast a shadow on the application running in that space. They scale the whole screen even they are not meant to do

**Comment by PapyElGringo** [comment]
Screen please :)

**Comment by UbadahJ** [comment]
![Screenshot from 2019-07-07 04-03-04](https://user-images.githubusercontent.com/26687928/60757224-19e03600-a021-11e9-81f1-eae290d53bd3.png)
This is when Android studio is loading (showing splash screen)

**Comment by UbadahJ** [comment]
![Screenshot from 2019-07-06 19-08-52](https://user-images.githubusercontent.com/26687928/60757239-9541e780-a021-11e9-9fbd-6dcaa9c587cc.png)
And almost every dialog is being treated as separate window

**Comment by nununoisy** [comment]
Further, windows with minimum sizes set (like GNOME Tweaks even) cover other windows in tiling mode. It should be possible to detect this and scale other windows accordingly.

**Comment by PapyElGringo** [comment]
Can you try with last commit?

**Comment by UbadahJ** [comment]
Android Studio dialog work much better where only issue remains of splash screen showing a shadow on all other windows in the work-space. Also there is no titlebar visible (as well as in Skype, Intellj Idea and Pycharm) and sometimes after it has opened it must be refocused using Alt+Tab before being visible

**Comment by UbadahJ** [comment]
Also it may not be related but the same dialog problems persist in Intellj Idea and Pycharm with titlebar issue and focus issue

**Comment by StanSvec** [comment]
@UbadahJ The dialog problem in IntelliJ IDEA is discussed in this issue: https://github.com/PapyElGringo/material-shell/issues/54
