### ISSUE TITLE
Internet tab is unresponsive on boot.

### ISSUE THREAD

**Issue by PenetratingShot** [PapyElGringo/material-shell#34]
You can't interact with the "Internet" tab, but when you open an application from the dock that's in the internet tab, it indicates that the application is open. 

The only way to fix is this to go to a new tab and then back to the Internet tab.

**Comment by PapyElGringo** [comment]
Can I get a screenshot of your desktop? What do you mean by open an application from the dock?

**Comment by PapyElGringo** [comment]
Can you retry the last version?

**Comment by PapyElGringo** [comment]
It's should be fixed in the last commit. Check and close if it's good for you now;

**Comment by PapyElGringo** [comment]
Closing by anticipation don't hesitate to reopen if needed
