### ISSUE TITLE
Material Shell doesn't acquire certain applications

### ISSUE THREAD

**Issue by alexbuzzbee** [PapyElGringo/material-shell#39]
I use an RSS reader called RSS Guard. While everything else on my system works more-or-less correctly, RSS Guard's main window does not get correctly picked up by Material Shell. As a result, the window remains floating (over my Web browser's window) when the application is launched, with no window decorations or way of moving it to another tab.

**Comment by PapyElGringo** [comment]
Still an issue?

**Comment by alexbuzzbee** [comment]
After `git pull`ing a new version and restarting GNOME, this appears to be fixed under both X11 and Wayland. Thanks!
