### ISSUE TITLE
Screenshots cannot be taken of windows that aren't in the same category as the screenshot window

### ISSUE THREAD

**Issue by Merlin04** [PapyElGringo/material-shell#41]
I can't take a screenshot of a window that's in one category because my screenshot app opens up in the "other" tab. I can only take a screenshot if I drag the window from the "other" workspace to the workspace with the window I want to screenshot using the menu button in the corner, or if I have two monitors (the other monitor shows "all applications").

**Comment by PapyElGringo** [comment]
It's should be fixed in the last commit. Check and close if it's good for you now;

**Comment by PapyElGringo** [comment]
Closing by anticipation don't hesitate to reopen if needed
