### ISSUE TITLE
keybinding to move windows around

### ISSUE THREAD

**Issue by kvaneesh** [PapyElGringo/material-shell#43]
Can we provide keybinding to move windows around? Is it possible to get a  Super-C followed by Super x sequence so that it becomes cut and exchange?

**Comment by kvaneesh** [comment]
Also, a keybinding to resize the window would also be nice. Even a mouse-based window resize that redraw the tiles would also help.

**Comment by frostspanner** [comment]
I would be happy with just super+shift+WASD keys to move the window where the focus would go.

**Comment by nununoisy** [comment]
`[Super+mousedrag]`

**Comment by PapyElGringo** [comment]
Done
