### ISSUE TITLE
title bar not shown?

### ISSUE THREAD

**Issue by kvaneesh** [PapyElGringo/material-shell#44]
For applications like emacs, I don't find a title bar displayed? That is also true for LibreOffice. Is there a config to show title bar?

**Comment by PapyElGringo** [comment]
Nop we decided to remove titlebar when it's possible to increase the vertical space available for the apps.
Why do you need the titlebar?

**Comment by kvaneesh** [comment]
Applications like emacs can put additional details on the title bar. ( like the full path of the file opened in a window/buffer)

**Comment by PapyElGringo** [comment]
Oh there is not other way to get the info? Unfortunately there is no option to toggle the titles bar.

**Comment by kvaneesh** [comment]
Is there anything i can do for emacs alone that I will help me to get the title bar?

**Comment by kvaneesh** [comment]
--- a/extension.js
+++ b/extension.js
@@ -5,7 +5,6 @@ const {
 } = Me.imports.module.disableIncompatibleExtensionsModule;
 const { LeftPanelModule } = Me.imports.module.leftPanel.leftPanelModule;
 const { SuperWorkspaceModule } = Me.imports.module.superWorkspaceModule;
-const { NoTitleBarModule } = Me.imports.module.noTitleBarModule;
 const { HotKeysModule } = Me.imports.module.hotKeysModule;
 const { RequiredSettingsModule } = Me.imports.module.requiredSettingsModule;
 const { TilingModule } = Me.imports.module.tilingModule;
@@ -26,7 +25,6 @@ function init() {
         new LeftPanelModule(),
         new TilingModule(),
         new SuperWorkspaceModule(),
-        new NoTitleBarModule(),
         new HotKeysModule()
     ];
 }

That got the titlebar, but then disabled panel and default window placements.

**Comment by kvaneesh** [comment]
It would be nice to enable selecting modules from the settings window. What I really need is the Tiling Module alone. I can use AutoMoveWindows official extension for window placement and Switcher extension for switching to the application? Yes, that is different from i3. But if we can achieve that my module selection option, why not support that?

**Comment by PapyElGringo** [comment]
someone decided to fork this to get what you want https://github.com/PapyElGringo/material-shell/issues/101
