### ISSUE TITLE
Option to move clock to top right corner 

### ISSUE THREAD

**Issue by Chrysostomus** [PapyElGringo/material-shell#46]
The current layout is excellent from window management point of view, but clock would be easier to read if it was in single line. Therefore I would suggest making the placement of the clock a toggleable option.

**Comment by PapyElGringo** [comment]
There is several reasons that make it's not a good idea:
1) The real top-panel is on the left-panel it's just has been manipulated to be vertical and from a coding point of view the clock hasn't moved really. Moving it's elsewhere would be a new feature to maintained and I want to have the less possible.
2) From structural point of view and from UX point of view everything in the left-panel is related to the "Computer" like workspaces, system informations, notifications, clock, systray. And everything at the right of the left-panel is related to a "Single workspace" task list, current tiling layouts, windows. And clock is really a system things.
3) This is related to the 2) but there isn't a single top-panel. In fact there is a top-panel for every workspaces you can see during the workspace switch animations there are multiple panel. Duplicating the clock would be weird to me.
4) The top-bar available space could be seem to be wast of space but if you have 3/4 apps opens every space is needed to display correctly the tabs.

**Comment by Chrysostomus** [comment]
Thank you for your response! Makes perfect sense.
