### ISSUE TITLE
Icons are giant.

### ISSUE THREAD

**Issue by LyesSaadi** [PapyElGringo/material-shell#47]
Hi!

Following the resolution of #11, I updated material-shell, and go this:
![Capture d’écran du 2019-07-08 16-55-37](https://user-images.githubusercontent.com/33597258/60824191-0fe54100-a1a1-11e9-8c4a-25e7aeb3b7aa.png)
Is it normal or a scaling error ?

Btw, I have a 200% HDPI scaling and giant icons with all applications.

**Comment by PapyElGringo** [comment]
Can you join me on discord to fix this asap?

**Comment by PapyElGringo** [comment]
It's probably related to this [line](https://github.com/PapyElGringo/material-shell/blob/9e26143345bc206f7fccb4668abe3b2db5818699/widget/taskBar.js#L272) Could you try to remove the scaleFactor here?

**Comment by LyesSaadi** [comment]
Hi! By removing the line, it's back to normal!
![Capture d’écran du 2019-07-08 17-51-43](https://user-images.githubusercontent.com/33597258/60827809-ef20e980-a1a8-11e9-8c2a-14ad018c91cb.png)

**Comment by PapyElGringo** [comment]
That's strange because if you remove all the line you should get and error for `this.iconSize is not defined`

**Comment by PapyElGringo** [comment]
And I can't reproduce the issue by scaling to 200% :S

**Comment by LyesSaadi** [comment]
By the line, I meant the scale factor.

**Comment by PapyElGringo** [comment]
Well I pushed this !

**Comment by LyesSaadi** [comment]
Maybe the icons in gnome are related to the resolution of the screen and not to the scale factor ? I have a 2880 x 1800 screen.
