### ISSUE TITLE
Ability to hide the top and left panels to be in fullscreen mode

### ISSUE THREAD

**Issue by PapyElGringo** [PapyElGringo/material-shell#49]
Add the ability to toggle to the panels to increase the space for windows and still be able to navigate around with keyboard shortcuts

**Comment by nununoisy** [comment]
Optionally you could just send a message to the client window to enter fullscreen like AwesomeWM did when you pressed Mod+F.

**Comment by PapyElGringo** [comment]
Yep but here it's not really the same idea. The idea here is not have only one app fullscreen but instead all the workspaces. You can see this like a "zen mode"

**Comment by nununoisy** [comment]
Got it. The bars seem to disappear whenever a window is fullscreen - would you be able to reuse the handler code (or is it not your code)?

**Comment by PapyElGringo** [comment]
The current fullscreen feature is a bit bugged because if while you are fullscreen you navigate to another workspace and come back the top-panel will be visible. I need to also fix this
