### ISSUE TITLE
Random glitches when switching beteween different IntelliJ windows, dimming windows

### ISSUE THREAD

**Issue by koryl** [PapyElGringo/material-shell#54]
When there are open few windows of IntelliJ and you try to switch between them, you can see some random glitches on the screen.
Another issue is weird "dimming" after clicking on some specific interface elements (e.g. Maven toolbar) or using "split screen" feature when multiple instances of IntelliJ are open.

OS: Ubuntu 19.04

**Comment by isantop** [comment]
I've also noticed that some applications will be darkened randomly when I go to interact with them. It seems to be more common if it spawns a modal dialog.

**Comment by DrDoctor13** [comment]
Full screen windows on dual-monitor setups are also subjected to random dimming, no modal dialogs required. Only fix I can find is restarting the shell

**Comment by derixithy** [comment]
Same problems with multi monitor screens, but swithing categories seems to fix it for a minute or 2

**Comment by koryl** [comment]
> Same problems with multi monitor screens, but swithing categories seems to fix it for a minute or 2
Best "temporary fix" is using shortcut alt + F2 and typing 'r' - after refresh it works fine for a certain period of time.

**Comment by PapyElGringo** [comment]
Can you check the last commit and give me feedbacks?

**Comment by koryl** [comment]
Yeah, sure. I will be testing it today and if everything will be alright I will close issue.

**Comment by StanSvec** [comment]
Are dialogs working fine for you? What happens when you press Ctrl+N or Ctrl+Shift+A? Is dialog displayed normally or the main window disappears and the dialog is displayed at the top left corner with rest of the screen black?

**Comment by StanSvec** [comment]
Okay, I'll document all issues I experienced when using IntelliJ IDEA. Need also to check that the AUR package contains the latest version. I'll get back when all completed.

**Comment by PapyElGringo** [comment]
The AUR package don't update automatically since it's a git AUR repo

**Comment by koryl** [comment]
@StanSvec No "screen black" for me. This is what's hapenning when using mentioned shortcuts in Full size mode:
![usingshortcut](https://user-images.githubusercontent.com/32077974/61444040-eb305c80-a94a-11e9-9c68-dd51838925e8.gif)

@PapyElGringo this is actually weird and confusing situation, especially when having multiple instances of IntelliJ because it hard to manage which instance are currently open. This little popup window is handled the same as normal. If it is possible, it would be better to handle such "popups" not in full screen, but it should remain on the top of an open window.

**Comment by koryl** [comment]
@StanSvec are you using the newest version?

**Comment by PapyElGringo** [comment]
@koryl  Are you ? lol

**Comment by StanSvec** [comment]
Tried with the newest version and it's same.

@koryl I see the same behavior as you show in the gif when I have tiling mode enabled (or how to call it), but when disabled (full screen?) then it behaves as I described in the previous comment.

@PapyElGringo There are more issues and almost all related to dialogs. I think the best if I record it and post as a gif as well. Any recommendations for an app recoding screen to gif like you used in your demo? I'll do it no later than next day.

**Comment by PapyElGringo** [comment]
Well this is currently the behavior I got https://streamable.com/mv36y

**Comment by StanSvec** [comment]
@PapyElGringo It works absolutely correct for you. Then I have no clue why @koryl and I experience those issues. :| I double-checked that it was tested with the current Git master version. Any idea what else we can try?

**Comment by koryl** [comment]
I've just tried these steps:
- disable extension
- run alt + F2 and 'r'
- remove directory with extension
- clone again repo
- enable extension
- run alt + F2 and 'r'
No success with this popup.
Good thing there is no glitches and blacked windows ;)

**Comment by StanSvec** [comment]
Also disabled, deleted directory, restarted, cloned again and no luck. @PapyElGringo Any other idea why we are not able to see the fixes. I really like using your extension, but these dialog problems forced me to disable it as I use IntelliJ product extensively.

**Comment by isantop** [comment]
I continue to have issues with any application which spawns a dialog as part of its opening. Good examples include Audacity and Hexchat.

**Comment by pvoid** [comment]
Had the same issue on wayland. Tried to fix it in this PR https://github.com/PapyElGringo/material-shell/pull/96

**Comment by PapyElGringo** [comment]
Is that fixed?I hopefully fixed this issue in the last commits. Please give me feedbacks :)

**Comment by StanSvec** [comment]
@PapyElGringo No dialog issues after brief checks in IDEA and PyCharm! Also no problems on my system (Antergos + Wayland) when switching between several IDEA windows or when opening Maven toolbar. Great job :)

**Comment by koryl** [comment]
@PapyElGringo No problems anymore, closing this issue.
