### ISSUE TITLE
Two monitors on lock screen makes top bar show

### ISSUE THREAD

**Issue by Merlin04** [PapyElGringo/material-shell#59]
When I have two monitors connected to my computer (my laptop screen and an external display) and the computer is on the lock screen, the top bar shows. This doesn't occur when there is only one monitor connected.

**Comment by PapyElGringo** [comment]
Well I personally have 2 monitor and don't experience this issue. Does it happens to other peoples?

**Comment by arjvik** [comment]
Nope, not here

**Comment by PapyElGringo** [comment]
This hasn't been reproduced.
