### ISSUE TITLE
Crash when an app category is empty

### ISSUE THREAD

**Issue by paradoxxxzero** [PapyElGringo/material-shell#6]
I currently have no games installed and therefore this line:

https://github.com/PapyElGringo/material-shell/blob/master/module/workspaceEnhancer/workspaceEnhancerModule.js#L721

returns null and causes the following crash:
```
JS ERROR: TypeError: apps is undefined
_loadApps@~/.local/share/gnome-shell/extensions/material-shell@papyelgringo/module/workspaceEnhancer/categorizedAppCard.js:38:29
```

**Comment by PapyElGringo** [comment]
The crash has been fixed but we need to remove empty category
