### ISSUE TITLE
Implement a system tray?

### ISSUE THREAD

**Issue by Luke-Nukem** [PapyElGringo/material-shell#61]
As in the old tray where icons like Steam would live. Any chance of this happening?
I currently use flatpak Steam, and if I accidentally close it, there is no way to open it back up besides killall then re-run it because you can run multiple instances of it with flatpak (also a big issue on Gnome standard).
I also have other tray things like owncloud, protonmail bridge etc, so yeah, kinda need this.

**Comment by aymanbagabas** [comment]
You could use https://github.com/ubuntu/gnome-shell-extension-appindicator

**Comment by PapyElGringo** [comment]
There is some other extensions that handle it but It's seem that none of them work correctly with Material-shell... We should improve the support for them.

**Comment by Luke-Nukem** [comment]
Hmm, TopIcons Redux seemed to work for a little while in a vertical arrangement, I'm not sure at which point it stopped though.

**Comment by Luke-Nukem** [comment]
Ah... that's interesting. If I have TopIcons Redux enabled before I enable Material Shell, the tray icons switch to vertical, but if I do a shell restart it reverts back to horizontal tray.

**Comment by kvaneesh** [comment]
That switch to horizontal tray impacts usage of the desktop. One of the workarounds i was trying was to see if i can place the system tray in the horizontal panel before layout switcher?

**Comment by Luke-Nukem** [comment]
> place the system tray in the horizontal panel before layout switcher

That would likely work quite well I suspect. Actually I wouldn't mind having the time/date there too as it becomes awkward to read in the bottom left vertical position.

Maybe [tray][date/time][layouts]?

**Comment by PapyElGringo** [comment]
I don't understand why instead trying to fix the bug you want to change all the layout? Anyway you may be interested by https://github.com/PapyElGringo/material-shell/issues/46#issuecomment-509296546

**Comment by Luke-Nukem** [comment]
@PapyElGringo it's neither really, was just throwing around ideas.

**Comment by kvaneesh** [comment]
> I don't understand why instead trying to fix the bug you want to change all the layout? Anyway you may be interested by [#46 (comment)](https://github.com/PapyElGringo/material-shell/issues/46#issuecomment-509296546)

Will that be a fix for material-shell or system tray extension? The system tray icons appear vertical in some case. Once I suspend and resume it redraws them horizontally.

**Comment by PapyElGringo** [comment]
The system tray extensions should work correctly now
