### ISSUE TITLE
Add terminal emulators to "development" section

### ISSUE THREAD

**Issue by donnellycolton** [PapyElGringo/material-shell#67]
Currently, terminal emulators are not displayed in any of the workspace sections. Change this by adding them to development section

**Comment by tilda** [comment]
The categories of applications depend on the categories laid out in the .desktop file for the application. Add `Development` to the desktop file for your terminal emulator and it should appear

**Comment by donnellycolton** [comment]
@tilda I believe that 'TerminalEmulator' should be included in the Development section by default, though, not a pick'n'choose or manual editing of .desktop files for each app I want to show.

Either default selection or some kind of menu in the extension settings I think would work fine.

**Comment by tilda** [comment]
Fair; that is just a little workaround for now. But hopefully #71 gets merged :)

**Comment by PapyElGringo** [comment]
Well gus I'm not convinced that terminal emulator is only related to development ! He is currently in no categories because "Orphans app" open in the current workspace and I believe that peoples used terminal in many places.

**Comment by anakaiti** [comment]
That makes sense. I think this should be postponed until someone implements custom categories. In the meantime users should just patch their own files.

**Comment by donnellycolton** [comment]
Papy I think development may be the best location for it of the current categories, granted it doesn't really 'fit in' anywhere else. However, custom categories seems like a good way to get this functionality as opt-in. I'll close this issue since to reflect that.
