### ISSUE TITLE
Hide system title bar in "maximized" layout

### ISSUE THREAD

**Issue by donnellycolton** [PapyElGringo/material-shell#68]
Hide system title bar of apps when layout manager is set to "maximized" mode. This is redundant since there's already a close button in the top windows bar.

**Comment by PapyElGringo** [comment]
Well since the apps titles bars should always be hided Im not sure to understand what you are asking for

**Comment by nununoisy** [comment]
Some GNOME programs add custom titlebar buttons which can't be hidden, like the default PDF viewer. This isn't a material-shell bug, and it isn't a bug.

**Comment by donnellycolton** [comment]
Papy: I'm not experiencing hidden title bar on any apps. See screenshot: there is a title bar for VSCode that is default, and the title bar along the top provided by material shell. This is redundant.

![Screenshot from 2019-07-17 20-57-59](https://user-images.githubusercontent.com/23486351/61421550-8686ea80-a8d5-11e9-84ba-914af90c1fdf.png)

However, nununoisy brings up a good point: some apps incorporate vital menu icons in their title bars (the default file explorer does this, as well), which would be difficult to account for.

**Comment by nununoisy** [comment]
@donnellycolton Do you have any other extensions enabled which could conflict?

**Comment by PapyElGringo** [comment]
@donnellycolton You need to set the title bar of vscode to native. Because now by default they use the "custom" titlebar that cannot be removed. `window.titleBarStyle: native`

**Comment by PapyElGringo** [comment]
You can do the same on google chrome aswell and other apps
