### ISSUE TITLE
Support light version?

### ISSUE THREAD

**Issue by xasx** [PapyElGringo/material-shell#69]
Is there any interest in providing a light version of this awesome piece of software?

I prefer light versions over dark ones, at daytime - so I would definitely be interested!

Any statement or hint on how to contribute this is highly appreciated.

Thanks :smile:

**Comment by PapyElGringo** [comment]
Yep of course ! But we need to improve the theming capabilities of Material-shell first!

**Comment by nununoisy** [comment]
I have a modified `stylesheet.scss` that will allow for a light theme. I am putting finishing touches on it then I will submit a PR.

**Comment by nununoisy** [comment]
![Light theme in action using Plata-Lumine](https://user-images.githubusercontent.com/9949555/61421648-dd33fa80-a8bc-11e9-94cb-4125254e1b6a.png)

**Comment by nununoisy** [comment]
![Light theme with Plata-Lumine](https://user-images.githubusercontent.com/9949555/61421674-f046ca80-a8bc-11e9-9ee2-84729394b105.png)

**Comment by nununoisy** [comment]
![Another shot with the category card](https://user-images.githubusercontent.com/9949555/61421727-2b48fe00-a8bd-11e9-98cc-bfc115a37dfa.png)

**Comment by nununoisy** [comment]
My much better light theme is now at #82.

**Comment by nununoisy** [comment]
This was fixed with the Theme Update (#132)

@PapyElGringo I think you should close this

**Comment by xasx** [comment]
Let me quickly verify, I'll close then immediately.

**Comment by xasx** [comment]
I see the light version on master, however, gnome-shell exhausts my CPU when launching Chrome.

Anyway, we can consider this done so far since I bet it is the same for me when differently colored.

Thank you @nununoisy
