### ISSUE TITLE
Freeze on gimp popup open

### ISSUE THREAD

**Issue by paradoxxxzero** [PapyElGringo/material-shell#8]
Every time gimp try to open a popup I got a system freeze (and no popup).

**Comment by logix2** [comment]
I've also experienced some complete system freezes with this extension. Once when I moved Gedit to a different monitor, and another time when I tried to save a file in Sublime Text (also on the non-main monitor). Let me know if you need extra info... unfortunately I'm not sure how to debug this.

**Comment by PapyElGringo** [comment]
Thanks for the feedbacks, the shell often restart is too many errors occurs. After a crash if you can extract the shell error `journalctl /usr/bin/gnome-shell -e` and host them somewhere for me?

**Comment by logix2** [comment]
Unfortunately Gnome Shell didn't restart for me, it just completely froze.

**Comment by PapyElGringo** [comment]
You should be able to get the logs at the restart then :( sorry about it's in high priority for me

**Comment by logix2** [comment]
This is what that command returns right now: [https://paste.ubuntu.com/p/p4hpPSx7Cy/](https://paste.ubuntu.com/p/p4hpPSx7Cy/)

**Comment by PapyElGringo** [comment]
I would need more and a better command should exist ^^

**Comment by logix2** [comment]
I just had another freeze, here's the journalctl output: [https://paste.ubuntu.com/p/HhnbCfHXhb/](https://paste.ubuntu.com/p/HhnbCfHXhb/). It appears there's some incompatibility with Ubuntu's AppIndicator extension?

**Comment by PapyElGringo** [comment]
That not the reason of the crash the log you gave don't go back enough in time let me check if I can find a better command.

**Comment by logix2** [comment]
The time was right until I rebooted... (with REISUB because of the freeze).

**Comment by PapyElGringo** [comment]
try `journalctl /usr/bin/gnome-shell --since today > gnome-shell-logs.txt` you should get a file called `gnome-shell-logs.txt` in the folder and send it to me :)

**Comment by logix2** [comment]
This is the log: https://transfer.sh/oTrAU/gnome-shell-logs.txt ... the errors should happen sometime in the last hour. Please let me know once you download the log so I can remove it for privacy reasons :)

**Comment by PapyElGringo** [comment]
Well I didn't ^^ send it to me in pm on discord if you are worried about data

**Comment by logix2** [comment]
I'll just repost it here: [https://mega.nz/#!uKhQBYAJ!gkaAj1_ElFr1ay7FKzaBE3h5pI1tMHVY7Bhn8eMwFzQ](https://mega.nz/#!uKhQBYAJ!gkaAj1_ElFr1ay7FKzaBE3h5pI1tMHVY7Bhn8eMwFzQ)

**Comment by PapyElGringo** [comment]
Do you have an approximatly timestamp?

**Comment by logix2** [comment]
There should be at least 2 crashes in the last hour from the log.
